Models/BusesModel.cs
namespace RutasBuses.Models
{
    public class BusesModel
    {
        public int id_Buses { get; set; }
        public string Capacidad { get; set;}
        public string Placa { get; set;}
        public DateTime Fecha_Fabricacion { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace RutasBuses.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/RutasModel.cs
namespace RutasBuses.Models
{
    public class RutasModel
    {
        public int id_Rutas { get; set; }
        public string Nombre_Ruta { get; set; }
        public decimal Valor_Pasaje { get; set; }
    }
}

Controllers/BusesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using RutasBuses;
using RutasBuses.Models;
using RutasBuses.Repositories;

namespace RutasBuses.Controllers
{
    public class BusesController : Controller
    {
        private readonly IBusesRepositories _busesRepository;

        public BusesController(IBusesRepositories busesRepository)
        {
            _busesRepository = busesRepository;
        }

        public IActionResult Index()
        {
            return View(_busesRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            var rutasBuses = _busesRepository.GetAll();

            ViewBag.RutasBuses = new SelectList(rutasBuses,
                                       nameof(RutasModel.id_Rutas),
                                       nameof(RutasModel.Nombre_Ruta));

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BusesModel buses)
        {
            try
            {
                _busesRepository.Add(buses);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                return View(buses);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var buses = _busesRepository.GetBusesById(id);
            var rutas = _busesRepository.GetAll();

            if (buses == null)
            {
                return NotFound();
            }

            ViewBag.RutasBuses = new SelectList(
                                       rutas,
                                       nameof(BusesModel.id_Buses),
                                       nameof(BusesModel.Capacidad),
                                       buses?.id_Buses
                                       );

            return View(buses);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BusesModel buses)
        {
            try
            {
                _busesRepository.Edit(buses);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                return View(buses);

            }
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RutasBuses.Models;
using System.Diagnostics;

namespace RutasBuses.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RutasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RutasBuses.Models;
using RutasBuses.Repositories;

namespace RutasBuses.Controllers
{
    public class RutasController : Controller
    {
        private readonly IRutasRepository _rutasRepository;

        public RutasController(IRutasRepository rutasRepository)
        {
            _rutasRepository = rutasRepository;
        }

        public IActionResult Index()
        {
            return View(_rutasRepository.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            var rutasBuses = _rutasRepository.GetAll();

            ViewBag.RutasBuses = new SelectList(rutasBuses,
                                       nameof(RutasModel.id_Rutas),
                                       nameof(RutasModel.Nombre_Ruta));

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RutasModel rutas)
        {
            try
            {
                _rutasRepository.Add(rutas);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                return View(rutas);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var rutas = _rutasRepository.GetRutasById(id);
            var buses = _rutasRepository.GetAll();

            if (rutas == null)
            {
                return NotFound();
            }

            ViewBag.RutasBuses = new SelectList(
                                       buses,
                                       nameof(RutasModel.id_Rutas),
                                       nameof(RutasModel.Nombre_Ruta),
                                       rutas?.id_Rutas
                                       );

            return View(rutas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(RutasModel rutas)
        {
            try
            {
                _rutasRepository.Edit(rutas);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                return View(rutas);

            }
        }
    }
}

Views/Buses/Create.cshtml
@model BusesModel

@{
    ViewData["Title"] = "Nuevo Bus";
}

<h1>Nuevp Bus</h1>
<hr />

<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mb-3">
                <label asp-for="id_Buses" class="control-label"></label>
                <input asp-for="id_Buses" class="form-control" />
                <span asp-validation-for="id_Buses" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Capacidad" class="control-label"></label>
                <select class="form-select" asp-for="Capacidad" asp-items="@ViewBag.rutasBuses">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="Capacidad" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />

                <a asp-action="Index">Regresar al listado</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Buses/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Buses/Edit.cshtml
@model BusesModel

@{
    ViewData["Title"] = "Editar Bus";
}

<h1>Editar Bus</h1>
<hr />

<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mb-3">
                <label asp-for="id_Buses" class="control-label"></label>
                <input asp-for="id_Buses" class="form-control" />
                <span asp-validation-for="id_Buses" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Capacidad" class="control-label"></label>
                <select class="form-select" asp-for="Capacidad" asp-items="@ViewBag.RutasBuses">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="Capacidad" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />

                <a asp-action="Index" class="btn btn-danger">Regresar al listado</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Buses/Index.cshtml
@model IEnumerable<BusesModel>
@{
    ViewData["Title"] = "Listado de Buses";
}

<h1>Listado de Buses</h1>

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="mt-3 mb-3">
                <a asp-action="Create" asp-controller="Buses" class="btn btn-success">
                    Nuevo Bus
                </a>
            </div>

            <table class="table table-bordered table-striped table-responsive" id="facultiesTable">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Capacidad</th>
                        <th>Placa</th>
                        <th>Fecha Fabricacion</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var buses in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(item => buses.id_Buses)</td>
                            <td>@Html.DisplayFor(item => buses.Capacidad)</td>
                            <td>@Html.DisplayFor(item => buses.Placa)</td>
                            <td>@Html.DisplayFor(item => buses.Fecha_Fabricacion)</td>
                            <td>
                                <a asp-controller="Buses"
                                   asp-action="Edit"
                                   asp-route-id="@buses.id_Buses"
                                   class="btn btn-primary">
                                    Editar
                                </a>
                                <a asp-controller="buses"
                                   asp-action="Delete"
                                   asp-route-id="@buses.id_Buses"
                                   class="btn btn-danger">
                                    Eliminar
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Rutas/Create.cshtml
@model RutasModel

@{
    ViewData["Title"] = "Nueva Ruta";
}

<h1>Nueva Ruta</h1>
<hr />

<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mb-3">
                <label asp-for="id_Rutas" class="control-label"></label>
                <input asp-for="id_Rutas" class="form-control" />
                <span asp-validation-for="id_Rutas" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Nombre_Ruta" class="control-label"></label>
                <select class="form-select" asp-for="Nombre_Ruta" asp-items="@ViewBag.rutasBuses">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="Nombre_Ruta" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />

                <a asp-action="Index">Regresar al listado</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Rutas/Edit.cshtml
@model RutasModel

@{
    ViewData["Title"] = "Editar Ruta";
}

<h1>Editar Ruta</h1>
<hr />

<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mb-3">
                <label asp-for="id_Rutas" class="control-label"></label>
                <input asp-for="id_Rutas" class="form-control" />
                <span asp-validation-for="id_Rutas" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Nombre_Ruta" class="control-label"></label>
                <select class="form-select" asp-for="Nombre_Ruta" asp-items="@ViewBag.RutasBuses">
                    <option value="">Seleccione</option>
                </select>
                <span asp-validation-for="Nombre_Ruta" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />

                <a asp-action="Index" class="btn btn-danger">Regresar al listado</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Rutas/Index.cshtml
@model IEnumerable<RutasModel>
@{
    ViewData["Title"] = "Listado de Rutas";
}

<h1>Listado de Rutas</h1>

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="mt-3 mb-3">
                <a asp-action="Create" asp-controller="Buses" class="btn btn-success">
                    Nuevo Bus
                </a>
            </div>

            <table class="table table-bordered table-striped table-responsive" id="facultiesTable">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre Ruta</th>
                        <th>Valor Pasaje</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var rutas in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(item => rutas.id_Rutas)</td>
                            <td>@Html.DisplayFor(item => rutas.Nombre_Ruta)</td>
                            <td>@Html.DisplayFor(item => rutas.Valor_Pasaje)</td>
                            <td>
                                <a asp-controller="Rutas"
                                   asp-action="Edit"
                                   asp-route-id="@rutas.id_Rutas"
                                   class="btn btn-primary">
                                    Editar
                                </a>
                                <a asp-controller="rutas"
                                   asp-action="Delete"
                                   asp-route-id="@rutas.id_Rutas"
                                   class="btn btn-danger">
                                    Eliminar
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RutasBuses</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RutasBuses.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RutasBuses</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rutas" asp-action="Index">Rutas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RutasBuses - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>